spring.application.name=demo
spring.devtools.restart.enabled=true

# Server
server.port=8080

# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/student_db
# mongodb://localhost:27017/student_db?connectTimeoutMS=5000&socketTimeoutMS=10000&serverSelectionTimeoutMS=5000&maxWaitTimeMS=2000&retryWrites=true&retryReads=true

# so the app can start even though can't connect to MongoDB
spring.data.mongodb.repositories.type=auto
# Disable the MongoDB health indicator so the app doesn't marked as DOWN if can't connect to MongoDB
management.health.mongodb.enabled=false

# Database circuit breaker
resilience4j.circuitbreaker.instances.database.register-health-indicator=false
resilience4j.circuitbreaker.instances.database.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.database.sliding-window-size=5
resilience4j.circuitbreaker.instances.database.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.database.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.database.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.database.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.database.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.database.record-exceptions=org.springframework.dao.DataAccessException,com.mongodb.MongoException
resilience4j.circuitbreaker.instances.database.ignore-exceptions=com.example.demo.exception.custom.StudentNotFoundException,com.example.demo.exception.custom.SubjectNotFoundException,com.example.demo.exception.custom.EnrollmentNotFoundException

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=student-group
spring.kafka.consumer.auto-offset-reset=earliest

